clone_depth: 1
version: "{build}"
image: Visual Studio 2017
platform:
  - x86
  - x64
environment:
  matrix:
    - compiler: msvc
install:
  - vcpkg install --triplet %PLATFORM%-windows --recurse fftw3 libsamplerate libsndfile sdl2
  - nuget install clcache -Version 4.1.0
  - nuget install python
build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir build
  - cd build
  - ps: $env:CMAKE_PLATFORM="$(if ($env:PLATFORM -eq 'x64') { 'x64' } else { '' })"
  - ps: $env:QT_SUFFIX="$(if ($env:PLATFORM -eq 'x64') { '_64' } else { '' })"
  - ps: $env:CLCACHE_DIR="%APPVEYOR_BUILD_FOLDER%/clcache"
  - set CC="%APPVEYOR_BUILD_FOLDER%/clcache.4.1.0/clcache-4.1.0/clcache.exe"
  - set CXX="%CC%"
  - cmake -DCMAKE_C_COMPILER="C:/projects.lmms-db2x2/clcache.4.1.0/clcache-4.1.0/clcache.exe" -DCMAKE_CXX_COMPILER="C:/projects.lmms-db2x2/clcache.4.1.0/clcache-4.1.0/clcache.exe" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_PREFIX_PATH=c:/Qt/5.12/msvc2017%QT_SUFFIX%;c:/tools/vcpkg/installed/%PLATFORM%-windows ..
  - cmake --build . -- /maxcpucount
  - cmake --build . --target tests
  - cmake --build . --target package
artifacts:
  - path: 'build\lmms-*.exe'
    name: Installer
cache:
  - c:/tools/vcpkg/installed
  - "%APPVEYOR_BUILD_FOLDER%/clcache"
